import streamlit as st
from streamlit_extras.bottom_container import bottom
# # Streamlit Landing Page

def main():
    st.logo("sanctum_t_l.png", size="large")

    # Header Section with Logo
    col1, col2 = st.columns([1, 12])
    with col1:
        st.image("logo_t.png", width=100)  # Replace 'path_to_logo.png' with the actual path to your logo image
    with col2:
        st.title("Welcome to GENQLVIZ")
        # st.markdown("#### (Prototype Built for MINEMATICS Pvt Ltd.)")
        st.markdown("### :orange[Your BI assistant Powered by AI!!!]")

    # Main Description with Bordered Box
    st.markdown(
        """
        <div style="border: 2px solid #4CAF50; padding: 15px; border-radius: 10px; background-color: #000000;">
            <p style="font-size: 16px;">GENQLVIZ is your ultimate assistant for SQL and data visualization tasks. Leverage the power of our SQL WiZard 
and Viz WiZard to streamline your workflow and enhance productivity.</p>
        </div>
        """,
        unsafe_allow_html=True
    )

    # SQL WiZard Features
    with st.container():
        st.markdown("#### SQL WiZard")
        st.markdown(
            """
            <div style="border: 2px solid #4CAF50; padding: 15px; border-radius: 10px; background-color: #000000;">
            <p style="font-size: 16px;">
            🔹 <b>Connect to your Database</b>: Seamlessly link your database for quick access.<br>
            🔹 <b>Ask the WiZard to Generate SQL</b>: Automate SQL query generation with ease.<br>
            🔹 <b>Run SQL generated by the WiZard</b>: Execute the queries instantly.<br>
            🔹 <b>Chat with the WiZard to enhance</b>: Refine your SQL queries with interactive guidance.
            </p>
            </div>
            """,
            unsafe_allow_html=True
        )

    # Viz WiZard Features
    with st.container():
        st.markdown("#### Viz WiZard")

        st.markdown(
            """
            <div style="border: 2px solid #4CAF50; padding: 15px; border-radius: 10px; background-color: #000000;">
            <p style="font-size: 16px;">
            🔹 <b>Ground Data in SQL WiZard</b>: Use structured data as the foundation.<br>
            🔹 <b>Ask the WiZard to Generate Python Viz Code</b>: Automatically create visualization code.<br>
            🔹 <b>Run Viz Code generated by the WiZard</b>: Execute and view your visualizations effortlessly.<br>
            🔹 <b>Chat with the WiZard to enhance</b>: Optimize and customize your visualizations.
            </p>
            </div>
            """,
            unsafe_allow_html=True
        )
    # Footer Section
    st.markdown("---")
    # st.markdown("#### Ready to supercharge your SQL and visualization tasks? Explore the sidebar to get started!")

    # Footer Section with magic wand and typing animation
    st.markdown("""
        <style>
            body {
            cursor: url('/images/logo.png'), auto;
            }
            .typing {
                font-family: 'Courier New', monospace;
                font-size: 1.5em;
                white-space: nowrap;
                overflow: hidden;
                border-right: 2px solid transparent;
                background: url('logo_t.png') no-repeat;
                background-size: contain;
                background-position: right center;
                width: 0;
                animation: typing 3s steps(60) 1s forwards, cursor-blink 0.5s step-start infinite, glitter 1.5s infinite;
            }

            .wand {
                position: absolute;
                animation: wand-move 1.5s infinite;
                font-size: 1.5em;
                left: -40px;
            }
            
            @keyframes typing {
                from { width: 0; }
                to { width: 71%;}
            }

            @keyframes wand-move {
                0% { left: -40px; }
                50% { left: 20px; }
                100% { left: -40px; }
            }
            @keyframes glitter {
            0% { text-shadow: 0 0 5px #fff, 0 0 10px #fff, 0 0 15px #ff0000, 0 0 20px #ff0000, 0 0 25px #ff0000, 0 0 30px #ff0000, 0 0 35px #ff0000; }
            50% { text-shadow: 0 0 5px #fff, 0 0 10px #fff, 0 0 15px #ff00ff, 0 0 20px #ff00ff, 0 0 25px #ff00ff, 0 0 30px #ff00ff, 0 0 35px #ff00ff; }
            100% { text-shadow: 0 0 5px #fff, 0 0 10px #fff, 0 0 15px #00ff00, 0 0 20px #00ff00, 0 0 25px #00ff00, 0 0 30px #00ff00, 0 0 35px #00ff00; }
        }                 
        </style>
        
        <div style="position: relative;">
            <span class="wand">🪄</span>
            <div class="typing">Ready to supercharge your SQL and visualization tasks? Explore the sidebar to get started!</div>
        </div>
        """,
        unsafe_allow_html=True)

    # Add a horizontal line for separation
    st.markdown("---")

    with bottom():
        st.write("**&copy; 2025 Sanctum Digital Solutions**")

main()